CMakeLists.txt
README.md
dependencies.yaml
src/iso15118/CMakeLists.txt
test/CMakeLists.txt
test/exi/cb/app_hand/CMakeLists.txt
test/exi/cb/iso20/CMakeLists.txt
test/iso15118/fsm/CMakeLists.txt
test/iso15118/states/CMakeLists.txt
test/v2gtp/CMakeLists.txt

Adding a dependencies yaml file for better handling dependencies (libfsm & catch2)

Adding dependencies.yaml

---

.ci/build-kit/build_and_test.sh
.github/workflows/build_and_test.yaml
src/iso15118/d20/config.cpp
test/iso15118/states/dc_charge_parameter_discovery.cpp

Added lint, build and test workflows.

Adding simple CI

---

.github/CODEOWNERS

Adding CI to codeowners file (because of Andreas)

Adding CI to codeowners file

---

src/iso15118/io/connection_plain.cpp

- Added defautl_socket_backlog.
- After accepting a client libiso prints out the client address.

Improve TCP socket

---

dependencies.yaml
src/iso15118/CMakeLists.txt
test/v2gtp/CMakeLists.txt

With the changes in libcbv2g, the CMakeLists.txt files of libiso15118 must also be adapted.

Updating libcbv2g

---

dependencies.yaml

Updating libcbv2g to last release v0.2.0

Updating libcbv2g to last release v0.2.0

---

3rd_party/CMakeLists.txt
CMakeLists.txt
include/iso15118/detail/helper.hpp
include/iso15118/io/connection_tls.hpp
src/iso15118/CMakeLists.txt
src/iso15118/io/connection_ssl.cpp
src/iso15118/io/connection_tls.cpp
src/iso15118/misc/helper.cpp
src/iso15118/tbd_controller.cpp

Adding OpenSSL support

---

include/iso15118/d20/context.hpp
include/iso15118/message/type.hpp
include/iso15118/session/feedback.hpp
src/iso15118/d20/context.cpp
src/iso15118/d20/state/authorization.cpp
src/iso15118/d20/state/authorization_setup.cpp
src/iso15118/d20/state/dc_cable_check.cpp
src/iso15118/d20/state/dc_charge_loop.cpp
src/iso15118/d20/state/dc_charge_parameter_discovery.cpp
src/iso15118/d20/state/dc_pre_charge.cpp
src/iso15118/d20/state/dc_welding_detection.cpp
src/iso15118/d20/state/power_delivery.cpp
src/iso15118/d20/state/schedule_exchange.cpp
src/iso15118/d20/state/service_detail.cpp
src/iso15118/d20/state/service_discovery.cpp
src/iso15118/d20/state/service_selection.cpp
src/iso15118/d20/state/session_setup.cpp
src/iso15118/d20/state/session_stop.cpp
src/iso15118/d20/state/supported_app_protocol.cpp
src/iso15118/session/feedback.cpp
src/iso15118/session/iso.cpp

Publish V2gMessageId

---

include/iso15118/detail/helper.hpp
include/iso15118/io/log_levels.hpp
include/iso15118/io/logging.hpp
src/iso15118/d20/context.cpp
src/iso15118/d20/context_helper.cpp
src/iso15118/d20/state/authorization_setup.cpp
src/iso15118/d20/state/dc_charge_parameter_discovery.cpp
src/iso15118/d20/state/schedule_exchange.cpp
src/iso15118/d20/state/service_detail.cpp
src/iso15118/d20/state/service_discovery.cpp
src/iso15118/d20/state/service_selection.cpp
src/iso15118/d20/state/session_setup.cpp
src/iso15118/d20/state/session_stop.cpp
src/iso15118/io/connection_plain.cpp
src/iso15118/io/connection_ssl.cpp
src/iso15118/io/connection_tls.cpp
src/iso15118/io/logging.cpp
src/iso15118/io/sdp_server.cpp
src/iso15118/io/socket_helper.cpp
src/iso15118/message/variant.cpp
src/iso15118/session/iso.cpp
src/iso15118/tbd_controller.cpp

See title
Right now everything was logged without any log levels. This PR adds log levels

Adding log levels

---

dependencies.yaml

Updated catch2 to latest stable release 3.6.0

---

include/iso15118/session/feedback.hpp
src/iso15118/d20/state/dc_charge_loop.cpp
src/iso15118/d20/state/session_setup.cpp
src/iso15118/d20/state/supported_app_protocol.cpp
src/iso15118/session/feedback.cpp
test/iso15118/CMakeLists.txt
test/iso15118/session/CMakeLists.txt
test/iso15118/session/feedback.cpp

- Adding evcc_id, selected_protocol & display_parameters to feedback
- Adding feedback unit tests

Adding evcc_id, selected_protocol & display_parameters to feedback

---

src/iso15118/io/connection_openssl.cpp

- Adding SO_REUSEADR & SO_REUSEPORT to connection_openssl
- Removing SSL_free & SSL_CTX_free
- Sometimes the port is in “use” when restarting `tbdcontroller` and the socket cannot be created.
- The custom_deleter for the two openssl contexts triggers a segfault, as the two contexts are already freed in the `close()`.

Small connection_openssl fixes

---

.ci/build-kit/build_and_test.sh
CMakeLists.txt
README.md
include/iso15118/d20/context.hpp
include/iso15118/detail/helper.hpp
include/iso15118/io/poll_manager.hpp
include/iso15118/message/authorization_setup.hpp
include/iso15118/tbd_controller.hpp
src/iso15118/CMakeLists.txt
src/iso15118/d20/config.cpp
src/iso15118/d20/context.cpp
src/iso15118/d20/state/schedule_exchange.cpp
src/iso15118/d20/state/session_setup.cpp
src/iso15118/io/connection_openssl.cpp
src/iso15118/io/connection_plain.cpp
src/iso15118/io/logging.cpp
src/iso15118/io/poll_manager.cpp
src/iso15118/io/sdp_server.cpp
src/iso15118/io/socket_helper.cpp
src/iso15118/message/ac_charge_loop.cpp
src/iso15118/message/authorization_setup.cpp
src/iso15118/message/dc_charge_loop.cpp
src/iso15118/message/schedule_exchange.cpp
src/iso15118/message/service_detail.cpp
src/iso15118/session/iso.cpp
test/CMakeLists.txt
test/iso15118/fsm/helper.hpp
test/iso15118/session/feedback.cpp
test/iso15118/states/schedule_exchange.cpp

Adding gcc compiler warnings `Wall, Wextra & Wno-unused-function` to libiso15118. At the same time, the warnings that occur are fixed here.
Right now there was no compiler warnings enabled. This PR should fix this.

Adding compiler warning

---

src/iso15118/d20/state/authorization_setup.cpp
src/iso15118/d20/state/dc_charge_parameter_discovery.cpp
src/iso15118/d20/state/service_detail.cpp
src/iso15118/d20/state/service_discovery.cpp
src/iso15118/d20/state/service_selection.cpp
src/iso15118/d20/state/session_setup.cpp
src/iso15118/d20/state/session_stop.cpp
src/iso15118/io/connection_mbedtls.cpp
src/iso15118/io/connection_openssl.cpp
src/iso15118/io/connection_plain.cpp
src/iso15118/io/sdp_server.cpp
src/iso15118/io/socket_helper.cpp
src/iso15118/message/variant.cpp
src/iso15118/session/iso.cpp

- trailing newlines should not be part of the logging strings itself, but rather be the responsibility of the output driver

chore(logging): remove trailing newline

---

src/iso15118/d20/state/dc_charge_parameter_discovery.cpp

Adding missing feedback `dc_max_limits`call. 
The EvseManager module needs the max limits from ChargeParameterDiscoveryReq message to set the correct voltage for the cable check. With this PR the max limits are published.

Adding feedback dc_max_limits call to dc_charge_parameter_discovery state

---

dependencies.yaml

Updated catch2 to latest stable release 3.7.1

---

include/iso15118/io/sdp_server.hpp
include/iso15118/message/authorization_setup.hpp
src/iso15118/tbd_controller.cpp
test/exi/cb/iso20/authorization_setup.cpp
test/iso15118/fsm/helper.hpp

Fixing the clang warnings/errors
Compiling libiso15118 with clang some errors/warnings are reported

Fixing clang compiler warnings

---

README.md

Updating README.md.
Adding a d20 feature list to show the current d20 feature support.
Without a feature list, it is quite difficult to get an overview of which D20 feature this library already contains.

Updating README.md and adding a d20 feature list

---

dependencies.yaml

Updating libcbv2g to latest version (v0.3.0)

---

CMakeLists.txt

Release v0.4.0

---

README.md

In the README.md, a short section "Acknowledgment" has been added to mention the funding of German Federal Ministry.
Too small change, did not create one.

Added logo for state funding

---

src/iso15118/message/service_detail.cpp

Added init for uninit param for ServiceDetailResponse

---

src/iso15118/message/authorization.cpp
src/iso15118/message/variant.cpp
test/exi/cb/iso20/authorization.cpp

Authorization messages add EV Side Se/Deserialization
#65 
- [x ] I have made corresponding changes to the documentation

Authorization messages add EV Side Se/Deserialization

---

src/iso15118/message/service_discovery.cpp
src/iso15118/message/variant.cpp
test/exi/cb/iso20/service_discovery.cpp

Service Discovery messages add EVSide Se/Deserialization
#67 

Service Discovery messages add EVSide Se/Deserialization

---

src/iso15118/message/service_selection.cpp
src/iso15118/message/variant.cpp
test/exi/cb/iso20/service_selection.cpp

ServiceSelection messages EVSide add Se/Deserialization
#66 

ServiceSelection messages add EVSide Se/Deserialization

---

include/iso15118/d20/session.hpp
src/iso15118/d20/session.cpp
test/iso15118/io/connection_openssl.cpp

- Removing unnecessary breaks
- Refactoring SelectedServiceParameters. Will be changed with adding AC. For every service there should be a seperate SelectedServiceParameters constructor.
See sonarcloud report: https://sonarcloud.io/project/issues?impactSoftwareQualities=RELIABILITY&issueStatuses=OPEN%2CCONFIRMED&id=EVerest_libiso15118

Removing unnecessary breaks, refactoring SelectedServiceParameters

---

src/iso15118/message/dc_charge_parameter_discovery.cpp
src/iso15118/message/variant.cpp
test/exi/cb/iso20/dc_charge_parameter_discovery.cpp

DCChargeParameterDiscovery messages add EVSide Se/Deserialization
https://github.com/EVerest/libiso15118/issues/70

DCChargeParameterDiscovery messages add EVSide Se/Deserialization

---

src/iso15118/message/dc_pre_charge.cpp
src/iso15118/message/variant.cpp
test/exi/cb/iso20/dc_pre_charge.cpp

DCPreCharge messages add EVSide Se/Deserialization
#73 

DCPreCharge messages add EVSide Se/Deserialization

---

src/iso15118/message/power_delivery.cpp
src/iso15118/message/variant.cpp
test/exi/cb/iso20/power_delivery.cpp

PowerDelivery messages add EVSide Se/Deserialization
#74 

PowerDelivery messages add EVSide Se/Deserialization

---

dependencies.yaml

Updating libcbv2g version to version 0.3.1

---

include/iso15118/detail/cb_exi.hpp
include/iso15118/message/common_types.hpp
src/iso15118/message/ac_charge_loop.cpp
src/iso15118/message/common_types.cpp
src/iso15118/message/dc_charge_loop.cpp
src/iso15118/message/power_delivery.cpp
src/iso15118/message/variant.cpp
test/exi/cb/iso20/dc_charge_loop.cpp

PowerDelivery messages add EVSide Se/Deserialization
#76 

DCChargeLoop messages add EVSide Se/Deserialization

---

src/iso15118/message/dc_welding_detection.cpp
src/iso15118/message/variant.cpp
test/exi/cb/iso20/dc_welding_detection.cpp

DCWeldingDetection messages add EVSide Se/Deserialization
#77 

DCWeldingDetection messages add EVSide Se/Deserialization

---

src/iso15118/message/session_stop.cpp
src/iso15118/message/variant.cpp
test/exi/cb/iso20/session_stop.cpp

SessionStop messages add EVSide Se/Deserialization
#78 

SessionStop messages add EVSide Se/Deserialization

---

test/CMakeLists.txt

Disable CodeCoverage when building with clang

---

README.md
include/iso15118/d20/config.hpp
include/iso15118/d20/session.hpp
include/iso15118/message/common_types.hpp
include/iso15118/message/service_detail.hpp
src/iso15118/d20/config.cpp
src/iso15118/d20/session.cpp
src/iso15118/d20/state/dc_charge_loop.cpp
src/iso15118/d20/state/dc_charge_parameter_discovery.cpp
src/iso15118/d20/state/schedule_exchange.cpp
src/iso15118/d20/state/service_detail.cpp
src/iso15118/message/service_detail.cpp
test/iso15118/states/dc_charge_loop.cpp
test/iso15118/states/dc_charge_parameter_discovery.cpp
test/iso15118/states/schedule_exchange.cpp
test/iso15118/states/service_detail.cpp
test/iso15118/states/service_discovery.cpp
test/iso15118/states/service_selection.cpp

Adding missing MCS services support from ISO15118-20 Amd
Missing MCS services in ISO15118-20 Amd

Adding MCS serivces

---

include/iso15118/d20/control_event.hpp
include/iso15118/d20/session.hpp
include/iso15118/session/feedback.hpp
include/iso15118/tbd_controller.hpp
src/iso15118/d20/state/authorization.cpp
src/iso15118/d20/state/service_selection.cpp
src/iso15118/d20/state/session_setup.cpp
src/iso15118/message/authorization_setup.cpp
src/iso15118/session/feedback.cpp
src/iso15118/session/iso.cpp
src/iso15118/tbd_controller.cpp
test/iso15118/session/feedback.cpp
test/iso15118/states/authorization.cpp
test/iso15118/states/authorization_setup.cpp
test/iso15118/states/dc_cable_check.cpp
test/iso15118/states/dc_charge_loop.cpp
test/iso15118/states/dc_charge_parameter_discovery.cpp
test/iso15118/states/dc_pre_charge.cpp
test/iso15118/states/dc_welding_detection.cpp
test/iso15118/states/power_delivery.cpp
test/iso15118/states/schedule_exchange.cpp
test/iso15118/states/service_detail.cpp
test/iso15118/states/service_discovery.cpp
test/iso15118/states/service_selection.cpp
test/iso15118/states/session_stop.cpp

feat(d20): Add dynamic update of supporting energy modes

---

.gitignore
include/iso15118/d20/context.hpp
include/iso15118/d20/ev_information.hpp
include/iso15118/message/supported_app_protocol.hpp
include/iso15118/session/feedback.hpp
src/iso15118/d20/state/session_setup.cpp
src/iso15118/d20/state/supported_app_protocol.cpp
src/iso15118/session/feedback.cpp
test/iso15118/session/feedback.cpp

Added new struct + callback to add EV information. This information is required for V2X with OCPP 2.1.

feat(EvInformation): Add new struct + feedback

---

include/iso15118/d20/context.hpp
include/iso15118/d20/state/authorization.hpp
include/iso15118/d20/state/schedule_exchange.hpp
include/iso15118/d20/states.hpp
include/iso15118/d20/timeout.hpp
include/iso15118/detail/d20/state/authorization.hpp
include/iso15118/detail/d20/state/schedule_exchange.hpp
include/iso15118/io/time.hpp
include/iso15118/session/iso.hpp
src/iso15118/CMakeLists.txt
src/iso15118/d20/context.cpp
src/iso15118/d20/state/authorization.cpp
src/iso15118/d20/state/schedule_exchange.cpp
src/iso15118/d20/timeout.cpp
src/iso15118/session/iso.cpp
test/iso15118/CMakeLists.txt
test/iso15118/d20/CMakeLists.txt
test/iso15118/d20/timeouts.cpp
test/iso15118/fsm/helper.hpp
test/iso15118/states/authorization.cpp
test/iso15118/states/schedule_exchange.cpp

Adding simple timeouts for the ISO15118-20 state machine
Timeouts were missing in the ISO15118-20 state machine. With this PR timeouts are added.

Adding simple ISO15118-20 timeouts

---

CMakeLists.txt

If this is only called with NO_DEFAULT_PATH yocto builds fail
Bump version to 0.7.1

Add missing find_package(everest-cmake)

---

dependencies.yaml

See title
The currently used catch2 version is one year old

Updating catch2 to v3.10.0

---

CMakeLists.txt
README.md

Updating readme.md -> AC, AC_BPT is now supported
